name: Post-build

on:
  # For security reasons, this workflow is separated from the test-and-build workflow and triggered by the `workflow_run` event following it.
  # The deployment jobs need access to the repository secrets,
  # however, workflows triggered by the `pull_request` event don't have access to the secrets for security reasons
  # because those workflows check out the PR's branch that may have malicious external contributors' changes,
  # so we can't use the `pull_request` event to trigger the deployment jobs.
  # Then, we have to run the deployment jobs in this separated workflow that is allowed to access the secrets because it runs in the context of the default branch which can be considered as a trusted branch.
  # It is a security good practice introduced in the GitHub's official blog, https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
  workflow_run:
    workflows: ["Test and Build"]
    types:
      - completed

permissions: {}

jobs:
  get-build-info:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      branch: ${{ steps.build-info.outputs.branch }}
      tag: ${{ steps.build-info.outputs.tag }}
      trigger-sha: ${{ steps.build-info.outputs.trigger-sha }}
      head-sha: ${{ steps.build-info.outputs.head-sha }}
      pr-number: ${{ steps.build-info.outputs.pr-number }}
    steps:
      - name: Download build info
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: build-info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Read build info
        id: build-info
        run: |
          echo "branch=$(cat branch)"
          echo "branch=$(cat branch)" >> $GITHUB_OUTPUT
          echo "tag=$(cat tag)"
          echo "tag=$(cat tag)" >> $GITHUB_OUTPUT
          echo "trigger-sha=$(cat trigger-sha)"
          echo "trigger-sha=$(cat trigger-sha)" >> $GITHUB_OUTPUT
          echo "head-sha=$(cat head-sha)"
          echo "head-sha=$(cat head-sha)" >> $GITHUB_OUTPUT
          echo "pr-number=$(cat pr-number)"
          echo "pr-number=$(cat pr-number)" >> $GITHUB_OUTPUT

  deploy-preview-wheel:
    needs: get-build-info
    if: ${{ needs.get-build-info.outputs.pr-number }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: Deploy wheel file to Cloudflare Pages
    outputs:
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - run: mkdir -p ${{ runner.temp }}/artifacts/

      - name: Download all the dists
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: streamlit-webrtc-${{ needs.get-build-info.outputs.trigger-sha }}
          path: ${{ runner.temp }}/artifacts/streamlit-webrtc

      - name: Deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >-
            pages deploy ${{ runner.temp }}/artifacts/streamlit-webrtc --project-name=streamlit-webrtc-preview --branch=${{ github.head_ref || github.ref_name }} --commit-hash=${{ github.sha }}

      - name: Comment on the PR to inform the deployment file URLs
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          ISSUE_NUMBER: ${{ needs.get-build-info.outputs.pr-number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const deploymentUrl = '${{ steps.deploy.outputs.deployment-url }}';

            // Get all files in the artifacts directory
            const artifactsDir = '${{ runner.temp }}/artifacts/streamlit-webrtc';
            const allFiles = fs.readdirSync(artifactsDir);
            // Filter to include only wheel (.whl) and source distribution (.tar.gz) files
            const files = allFiles.filter(file => file.endsWith('.whl') || file.endsWith('.tar.gz'));

            // Create message with links to each file
            let fileLinks = files.map(file => {
              const installCommand = `pip install ${deploymentUrl}/${file}`;
              return `- [${file}](${deploymentUrl}/${file})\n  \`\`\`bash\n  ${installCommand}\n  \`\`\``;
            }).join('\n');

            const message = `📦 Wheel files have been deployed to Cloudflare Pages:

            ${fileLinks}`;

            github.rest.issues.createComment({
              issue_number: process.env.ISSUE_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
